// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// example4:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUphixYPE9MdNf4Phum14XYzY5alQSlTI',
    appId: '1:751372776245:android:f3825ef58f5a3de9e3d27c',
    messagingSenderId: '751372776245',
    projectId: 'sahty-a6393',
    storageBucket: 'sahty-a6393.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwUB-Ey6-sVF2pE2UiswNl6MTROtjNIfo',
    appId: '1:751372776245:ios:66a85c80c2a8cd7fe3d27c',
    messagingSenderId: '751372776245',
    projectId: 'sahty-a6393',
    storageBucket: 'sahty-a6393.firebasestorage.app',
    iosBundleId: 'com.example4.sahty',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA36WIG2N05rTRHbGu1e8uIaXLMDwDx4Lg',
    appId: '1:751372776245:web:276742c97febdaf6e3d27c',
    messagingSenderId: '751372776245',
    projectId: 'sahty-a6393',
    authDomain: 'sahty-a6393.firebaseapp.com',
    storageBucket: 'sahty-a6393.firebasestorage.app',
    measurementId: 'G-5M2QTYMJH9',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwUB-Ey6-sVF2pE2UiswNl6MTROtjNIfo',
    appId: '1:751372776245:ios:66a85c80c2a8cd7fe3d27c',
    messagingSenderId: '751372776245',
    projectId: 'sahty-a6393',
    storageBucket: 'sahty-a6393.firebasestorage.app',
    iosBundleId: 'com.example4.sahty',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA36WIG2N05rTRHbGu1e8uIaXLMDwDx4Lg',
    appId: '1:751372776245:web:c7c4ecd3b2f705eee3d27c',
    messagingSenderId: '751372776245',
    projectId: 'sahty-a6393',
    authDomain: 'sahty-a6393.firebaseapp.com',
    storageBucket: 'sahty-a6393.firebasestorage.app',
    measurementId: 'G-L1E2B7XYS0',
  );

}